include: package:lint/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: true
    use_setters_to_change_properties: false
    avoid_function_literals_in_foreach_calls: false
    avoid_classes_with_only_static_members: false
