name: restaurant_asd
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # UI related
  cupertino_icons: ^1.0.0
  # Utilities
  lint: ^1.3.0
  # Stacked Architecture
  stacked: ^1.9.1+2
  stacked_services: ^0.7.2
  # Database
  sqflite: ^1.3.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Code Generator
  build_runner: ^1.10.2
  stacked_generator: ^0.1.2

flutter:
  uses-material-design: true
